name: VS Code Extension Build

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]

jobs:
  package-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.1
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build server
        run: pnpm -C server build

      - name: Bundle server into client
        run: pnpm -C client-vscode bundle:server

      - name: Build client bundle
        run: pnpm -C client-vscode bundle

      - name: Package VSIX
        run: pnpm -C client-vscode package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-lsl-lsp-vsix
          path: client-vscode/*.vsix

      - name: Add run summary
        env:
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          {
            echo "## ✅ VSIX artifact ready";
            echo;
            echo "- Open the run: ${RUN_URL}";
            echo "- Download from the Artifacts section: vscode-lsl-lsp-vsix";
            echo;
            echo "Tip (GitHub CLI):";
            echo "\`gh run download ${{ github.run_id }} -n vscode-lsl-lsp-vsix\`";
          } >> "$GITHUB_STEP_SUMMARY"

  release:
    name: Publish Release (on tags)
    needs: package-extension
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: vscode-lsl-lsp-vsix
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.vsix
          generate_release_notes: true
          fail_on_unmatched_files: true
